"use client";
import { useState } from "react";
import data from "@/data/admin-dashboard.json";
import { useToast } from "@/components/ui/toast-provider";
import { AdminPageHeader } from "@/components/admin/admin-shared";

export function AdminSettingsView({legal=false}:{legal?:boolean}){
 const toast=useToast();const[saving,setSaving]=useState(false);
 async function save(){setSaving(true);await new Promise(r=>setTimeout(r,350));setSaving(false);toast.success(legal?"Legal content saved in UI demo.":"Company settings saved in UI demo.")}
 if(legal)return <div className="ad-stack"><AdminPageHeader eyebrow="Trust & compliance" title="Legal Content" description="Keep registration details, copyright text and policy publishing status in one place."/><section className="ad-settings-grid"><div className="ad-form-stack"><article className="ad-card"><div className="ad-card-head"><div><p className="ad-kicker">Company identity</p><h2>Registration Details</h2></div></div><div className="ad-form-grid"><label className="ad-field"><span>GST Number</span><input defaultValue={data.legal.gst} placeholder="Add verified GST number only"/></label><label className="ad-field"><span>Registration / CIN</span><input defaultValue={data.legal.registration} placeholder="Add verified registration only"/></label></div></article><article className="ad-card"><div className="ad-card-head"><div><p className="ad-kicker">Policies</p><h2>Publishing Status</h2></div></div><div className="ad-policy-list"><div><strong>Privacy Policy</strong><span>{data.legal.privacyUpdated}</span><button>Edit</button></div><div><strong>Terms of Use</strong><span>{data.legal.termsUpdated}</span><button>Edit</button></div></div></article><article className="ad-card"><label className="ad-field"><span>Copyright Text</span><input defaultValue={data.legal.copyright}/></label></article><button className="ad-primary ad-save" onClick={save}>{saving?"Saving…":"Save Legal Content"}</button></div><aside className="ad-card ad-trust-card"><p className="ad-kicker">Important</p><h2>Do not invent legal data.</h2><p>Only verified GST, registration and legal text should be published. Empty fields are intentionally supported until real details are supplied.</p></aside></section></div>;

 return <div className="ad-stack"><AdminPageHeader eyebrow="Platform configuration" title="Company Settings" description="Manage the public-facing company identity, contact details and social links."/><section className="ad-settings-grid"><div className="ad-form-stack"><article className="ad-card"><div className="ad-card-head"><div><p className="ad-kicker">Brand</p><h2>Company Identity</h2></div></div><div className="ad-form-grid"><label className="ad-field"><span>Company Name</span><input defaultValue={data.settings.companyName}/></label><label className="ad-field"><span>Tagline</span><input defaultValue={data.settings.tagline}/></label></div></article><article className="ad-card"><div className="ad-card-head"><div><p className="ad-kicker">Contact</p><h2>Public Contact Details</h2></div></div><div className="ad-form-grid"><label className="ad-field"><span>Email</span><input defaultValue={data.settings.email}/></label><label className="ad-field"><span>Phone</span><input defaultValue={data.settings.phone}/></label><label className="ad-field ad-field-wide"><span>Location</span><input defaultValue={data.settings.location}/></label></div></article><article className="ad-card"><div className="ad-card-head"><div><p className="ad-kicker">Social</p><h2>Social Profiles</h2></div></div><div className="ad-form-grid"><label className="ad-field"><span>Instagram</span><input defaultValue={data.settings.instagram}/></label><label className="ad-field"><span>YouTube</span><input defaultValue={data.settings.youtube}/></label><label className="ad-field ad-field-wide"><span>LinkedIn</span><input defaultValue={data.settings.linkedin}/></label></div></article><button className="ad-primary ad-save" onClick={save}>{saving?"Saving…":"Save Settings"}</button></div><aside className="ad-card ad-settings-note"><p className="ad-kicker">CMS direction</p><h2>Database-driven later.</h2><p>This screen currently uses temporary JSON for UI approval. After approval, these fields should load from the Settings API and MongoDB.</p></aside></section></div>
}
