import { BadRequestException, ConflictException, Injectable, NotFoundException } from "@nestjs/common"; import { InjectModel } from "@nestjs/mongoose"; import { Types, type Model } from "mongoose"; import { AuditService } from "../../common/audit/audit.service"; import { pageMeta } from "../../common/dto/pagination.dto"; import { objectId } from "../../common/utils/object-id"; import { escapeSearch } from "../../common/utils/search"; import { MediaService } from "../media/media.service"; import { Project } from "../projects/project.model"; import { Casting } from "./casting.model"; import { CastingQueryDto,CreateCastingDto,UpdateCastingDto } from "./casting.dto";
@Injectable() export class CastingService {
 constructor(@InjectModel("Casting") private readonly castings:Model<Casting>,@InjectModel("Project") private readonly projects:Model<Project>,private readonly media:MediaService,private readonly audit:AuditService){}
 private serialize(casting:Casting|Record<string,unknown>){const item=casting as Casting; const coverId=item.coverMediaId?String(item.coverMediaId):undefined; const deadline=item.deadline?new Date(item.deadline):undefined; return {...casting,_id:String((casting as {_id:unknown})._id),projectId:item.projectId?String(item.projectId):undefined,coverMediaId:coverId,coverImage:coverId?this.media.urlsFor(coverId).large:undefined,closingSoon:item.status==="Open"&&!!deadline&&deadline.getTime()>Date.now()&&deadline.getTime()<Date.now()+7*86400000,acceptingApplications:item.published&&!item.archived&&item.status==="Open"&&(!deadline||deadline.getTime()>Date.now())};}
 listPublic(q:CastingQueryDto){return this.list(q,false)} listAdmin(q:CastingQueryDto){return this.list(q,true)}
 private async list(q:CastingQueryDto,admin:boolean){const filter:Record<string,unknown>={archived:false,...(admin?{}:{published:true,status:"Open"}),...(q.status?{status:q.status}:{}),...(q.category?{category:q.category}:{}),...(q.location?{location:new RegExp(escapeSearch(q.location.trim()),"i")} : {}),...(q.projectId?{projectId:objectId(q.projectId)}:{})}; if(q.search){const s=new RegExp(escapeSearch(q.search.trim()),"i");filter.$or=[{title:s},{role:s},{summary:s},{location:s}]}; const [items,total]=await Promise.all([this.castings.find(filter).sort({deadline:1,createdAt:-1}).skip((q.page-1)*q.limit).limit(q.limit).lean(),this.castings.countDocuments(filter)]); return {items:items.map((v)=>this.serialize(v)),meta:pageMeta(q.page,q.limit,total)};}
 async bySlug(slug:string){const x=await this.castings.findOne({slug,published:true,archived:false}).lean();if(!x) throw new NotFoundException("Casting call not found.");return this.serialize(x)} async byId(id:string){const x=await this.castings.findById(objectId(id)).lean();if(!x) throw new NotFoundException("Casting call not found.");return this.serialize(x)}
 private async validate(input:CreateCastingDto|UpdateCastingDto){if(input.ageMin!==undefined&&input.ageMax!==undefined&&input.ageMin>input.ageMax)throw new BadRequestException("Minimum age cannot exceed maximum age.");if(input.deadline&&input.shootDate&&new Date(input.deadline)>new Date(input.shootDate))throw new BadRequestException("Application deadline cannot be after the shoot date.");if(input.projectId&&!(await this.projects.exists({_id:objectId(input.projectId,"Project not found."),archived:false})))throw new BadRequestException("Project not found.");}
 async create(input:CreateCastingDto,actorId:string){await this.validate(input);await this.media.assertOwnedBy(actorId,[input.coverMediaId]);try{const x=await this.castings.create({...input,projectId:input.projectId?new Types.ObjectId(input.projectId):undefined,coverMediaId:input.coverMediaId?new Types.ObjectId(input.coverMediaId):undefined,createdBy:new Types.ObjectId(actorId),updatedBy:new Types.ObjectId(actorId)});if(x.published&&x.coverMediaId)await this.media.makePublic([String(x.coverMediaId)]);await this.audit.record({actorId,action:"casting.create",entityType:"casting",entityId:String(x._id),summary:x.title});return this.serialize(x.toObject())}catch(error:unknown){if(error&&typeof error==="object"&&"code" in error&&error.code===11000)throw new ConflictException("This casting-call slug is already in use.");throw error}}
 async update(id:string,input:UpdateCastingDto,actorId:string){await this.validate(input);await this.media.assertOwnedBy(actorId,[input.coverMediaId]);const update:Record<string,unknown>={...input,updatedBy:new Types.ObjectId(actorId)};if(input.projectId)update.projectId=new Types.ObjectId(input.projectId);if(input.coverMediaId)update.coverMediaId=new Types.ObjectId(input.coverMediaId);const x=await this.castings.findOneAndUpdate({_id:objectId(id),archived:false},{$set:update},{new:true,runValidators:true});if(!x)throw new NotFoundException("Casting call not found.");if(x.published&&x.coverMediaId)await this.media.makePublic([String(x.coverMediaId)]);await this.audit.record({actorId,action:"casting.update",entityType:"casting",entityId:id,summary:x.title});return this.serialize(x.toObject())}
 async close(id:string,actorId:string){const x=await this.castings.findOneAndUpdate({_id:objectId(id),archived:false},{$set:{status:"Closed",updatedBy:new Types.ObjectId(actorId)}},{new:true});if(!x)throw new NotFoundException("Casting call not found.");await this.audit.record({actorId,action:"casting.close",entityType:"casting",entityId:id,summary:x.title});return this.serialize(x.toObject())}
 async archive(id:string,actorId:string){const x=await this.castings.findByIdAndUpdate(objectId(id),{$set:{archived:true,published:false,status:"Closed",updatedBy:new Types.ObjectId(actorId)}},{new:true});if(!x)throw new NotFoundException("Casting call not found.");await this.audit.record({actorId,action:"casting.archive",entityType:"casting",entityId:id,summary:x.title});return {message:"Casting call archived.",id}}
}
