"use client";
import { useState, type FormEvent } from "react";
import { SiteFooter } from "@/components/site/site-footer";
import { SiteHeader } from "@/components/site/site-header";
import { PageIntro } from "@/components/site/page-intro";
import { api } from "@/services/api";
import { useToast } from "@/components/ui/toast-provider";

export default function CareersPage(){
 const toast=useToast(),[saving,setSaving]=useState(false);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(saving)return;const form=event.currentTarget,data=new FormData(form);setSaving(true);try{await api("/careers",{method:"POST",body:JSON.stringify({name:String(data.get("name")??""),email:String(data.get("email")??""),mobile:String(data.get("mobile")??""),role:String(data.get("role")??""),city:String(data.get("city")??"")||undefined,coverNote:String(data.get("coverNote")??""),resumeUrl:String(data.get("resumeUrl")??"")||undefined,portfolioUrl:String(data.get("portfolioUrl")??"")||undefined,linkedinUrl:String(data.get("linkedinUrl")??"")||undefined})});form.reset();toast.success("Application received.","Thank you. The team will contact you if your profile matches an opening.")}catch(error){toast.error("Unable to submit application.",error instanceof Error?error.message:undefined)}finally{setSaving(false)}}
 return <><SiteHeader/><main id="main-content"><PageIntro eyebrow="Careers" title="Build Meaningful Work With Us" description="Share your profile for production, creative, operational or platform opportunities." mediaAlt="Film production team" mediaKind="team"/><section className="site-section bg-[#fafafa]"><div className="site-shell grid gap-8 lg:grid-cols-[.75fr_1.25fr]"><aside className="site-card h-fit p-7 sm:p-8"><p className="site-kicker">Before you apply</p><h2 className="font-display mt-3 text-3xl font-semibold">Show us how you like to work.</h2><p className="mt-5 text-sm leading-6 text-[#666]">Use shareable HTTPS resume and portfolio links. Applications are reviewed against current and upcoming openings.</p></aside><form onSubmit={submit} className="site-card grid gap-5 p-7 sm:p-9"><div className="grid gap-5 sm:grid-cols-2"><label className="grid gap-2 text-sm font-semibold">Full Name<input className="field" name="name" required minLength={2}/></label><label className="grid gap-2 text-sm font-semibold">Email<input className="field" name="email" type="email" required/></label><label className="grid gap-2 text-sm font-semibold">Mobile<input className="field" name="mobile" required/></label><label className="grid gap-2 text-sm font-semibold">City<input className="field" name="city"/></label><label className="grid gap-2 text-sm font-semibold sm:col-span-2">Role / Area of Interest<input className="field" name="role" required/></label><label className="grid gap-2 text-sm font-semibold">Resume URL<input className="field" name="resumeUrl" type="url" placeholder="https://..."/></label><label className="grid gap-2 text-sm font-semibold">Portfolio URL<input className="field" name="portfolioUrl" type="url" placeholder="https://..."/></label><label className="grid gap-2 text-sm font-semibold sm:col-span-2">LinkedIn URL<input className="field" name="linkedinUrl" type="url" placeholder="https://..."/></label><label className="grid gap-2 text-sm font-semibold sm:col-span-2">Tell us about yourself<textarea className="field min-h-36" name="coverNote" required minLength={20} maxLength={5000}/></label></div><button disabled={saving} className="site-button site-button-primary justify-self-start" type="submit">{saving?"Submitting…":"Submit Application"}</button></form></div></section></main><SiteFooter/></>
}
